// 포트폴리오 디스플레이 설정 — 이 파일만 고치면 화면 내용이 바뀝니다.
// accent: 밝은 강조색(배경·라인), ink: 흰 배경 위 글자/숫자용 진한 색
// media 우선순위: video(있으면) → tall(세로로 천천히 스크롤) → image(줌인)
// 화면 녹화 영상을 넣으려면 assets/videos/ 에 MP4를 두고 video 경로를 적으세요.
window.PORTFOLIO = {
  owner: "재일 AI · 데이터 시스템",
  tagline: "제조 현장을 데이터로 연결하고, AI로 판단을 돕습니다.",
  rotateSeconds: 18,

  projects: [
    {
      title: "재일 시스템 허브",
      category: "플랫폼 포털",
      summary: "고객사별 제조 AI·에이전트·데이터·머신러닝 서비스를 한 화면에서 관리하는 통합 운영 허브",
      tags: ["서비스 카탈로그", "상태 모니터링", "도커 운영"],
      metrics: [["27", "운영 서비스"], ["5", "시스템 카테고리"]],
      url: "http://187.52.127.215:8600/",
      qr: "assets/qr/01.svg",
      image: "assets/shots/01-fold.png",
      tall: "assets/shots/01-tall.png",
      video: "",
      accent: "#3b82f6",
      ink: "#1d4ed8",
    },
    {
      title: "송월타월 제조AI 플랫폼",
      category: "통합 제조AI",
      summary: "생산·품질·설비·출하 현황을 AI 대시보드로 실시간 모니터링하고, 소비자발주부터 원부자재입고·인쇄공정까지 전 공정을 하나의 시스템으로 통합관리",
      tags: ["생산·품질·설비 통합 대시보드", "월별 불량률 추이 분석", "설비 가동률 모니터링"],
      metrics: [["4/5", "가동 설비"], ["12.5%", "불합격률"]],
      url: "http://187.52.127.215:8000/",
      qr: "assets/qr/02.svg",
      image: "assets/shots/02-fold.png",
      tall: "assets/shots/02-tall.png",
      video: "",
      accent: "#f59e0b",
      ink: "#b45309",
    },
    {
      title: "임진강김치 데이터 게이트웨이",
      category: "산업 IoT · 디지털 트윈",
      summary: "PLC 설비 데이터를 Modbus TCP로 수집하고 엣지 버퍼로 MES에 무손실 전송하는 수집 트윈",
      tags: ["Modbus TCP", "엣지 버퍼", "MES 연동"],
      metrics: [["22/22", "정상 장비"], ["700만+", "누적 전송"]],
      url: "http://srv1934103.hstgr.cloud:8025/edge",
      qr: "assets/qr/03.svg",
      image: "assets/shots/03-fold.png",
      tall: "",
      video: "",
      accent: "#22c55e",
      ink: "#15803d",
    },
    {
      title: "경동글로벌텍 제조AI 플랫폼",
      category: "통합 제조AI",
      summary: "견적·입고·공정·출하 전 과정을 10개 업무 모듈로 통합하고 AI Agent가 리드타임·설비·납기 리스크를 실시간으로 관제",
      tags: ["CAD 도면분석·견적AI", "공정 디지털 스레드", "통합 AI Agent"],
      metrics: [["10", "업무 모듈"], ["45", "업무 화면"]],
      url: "http://187.52.127.215:8020/",
      qr: "assets/qr/04.svg",
      image: "assets/shots/04-fold.png",
      tall: "assets/shots/04-tall.png",
      video: "",
      accent: "#8b5cf6",
      ink: "#6d28d9",
    },
    {
      title: "평창꽃순이김치 발효 머신러닝",
      category: "품질 AI",
      summary: "배합·절임·숙성 데이터로 김치 품질을 예측하고 배합·숙성 조건 최적화를 지원",
      tags: ["품질 예측", "모델 벤치마크", "배합 최적화"],
      metrics: [["420", "학습 로트"], ["3", "비교 모델"]],
      url: "http://187.52.127.215:8022/",
      qr: "assets/qr/05.svg",
      image: "assets/shots/05-fold.png",
      tall: "",
      video: "",
      accent: "#a3e635",
      ink: "#4d7c0f",
    },
  ],
};
