// 포트폴리오 디스플레이 설정 — 이 파일만 고치면 화면 내용이 바뀝니다.
// accent: 밝은 강조색(배경·라인), ink: 흰 배경 위 글자/숫자용 진한 색
// media 우선순위: video(있으면) → tall(세로로 천천히 스크롤) → image(줌인)
// 화면 녹화 영상을 넣으려면 assets/videos/ 에 MP4를 두고 video 경로를 적으세요.
window.PORTFOLIO = {
  owner: "재일 AI · 데이터 시스템",
  tagline: "제조 현장을 데이터로 연결하고, AI로 판단을 돕습니다.",
  rotateSeconds: 18,

  projects: [
    {
      title: "재일 시스템 허브",
      category: "플랫폼 포털",
      summary: "고객사별 제조 AI·에이전트·데이터·머신러닝 서비스를 한 화면에서 관리하는 통합 운영 허브",
      tags: ["서비스 카탈로그", "상태 모니터링", "도커 운영"],
      metrics: [["27", "운영 서비스"], ["5", "시스템 카테고리"]],
      url: "http://187.52.127.215:8600/",
      qr: "assets/qr/01.svg",
      image: "assets/shots/01-fold.png",
      tall: "assets/shots/01-tall.png",
      video: "",
      accent: "#3b82f6",
      ink: "#1d4ed8",
    },
    {
      title: "재일 프로젝트 관리",
      category: "프로젝트 관리",
      summary: "정부지원 제조AI 프로젝트의 단계별 일정·지연·임박 현황을 한눈에 추적하는 일정 관리 대시보드",
      tags: ["일정 추적", "PostgreSQL", "Vercel 배포"],
      metrics: [["8", "관리 프로젝트"], ["12", "추적 단계"]],
      url: "https://jaeil-project-manager.vercel.app/",
      qr: "assets/qr/02.svg",
      image: "assets/shots/02-fold.png",
      tall: "assets/shots/02-tall.png",
      video: "",
      accent: "#f59e0b",
      ink: "#b45309",
    },
    {
      title: "임진강김치 데이터 게이트웨이",
      category: "산업 IoT · 디지털 트윈",
      summary: "PLC 설비 데이터를 Modbus TCP로 수집하고 엣지 버퍼로 MES에 무손실 전송하는 수집 트윈",
      tags: ["Modbus TCP", "엣지 버퍼", "MES 연동"],
      metrics: [["22/22", "정상 장비"], ["700만+", "누적 전송"]],
      url: "http://srv1934103.hstgr.cloud:8025/edge",
      qr: "assets/qr/03.svg",
      image: "assets/shots/03-fold.png",
      tall: "",
      video: "",
      accent: "#22c55e",
      ink: "#15803d",
    },
    {
      title: "광성정밀 예지보전 머신러닝",
      category: "예지보전",
      summary: "프레스 설비 센서 신호로 잔여수명을 예측하고 우선 점검할 로트를 제시",
      tags: ["그래디언트 부스팅", "잔여수명 예측", "설비 스냅샷"],
      metrics: [["720", "분석 로트"], ["5.57시간", "잔여수명 평균오차"]],
      url: "http://187.52.127.215:8013/",
      qr: "assets/qr/04.svg",
      image: "assets/shots/04-fold.png",
      tall: "assets/shots/04-tall.png",
      video: "",
      accent: "#14b8a6",
      ink: "#0f766e",
    },
    {
      title: "평창꽃순이김치 발효 머신러닝",
      category: "품질 AI",
      summary: "배합·절임·숙성 데이터로 김치 품질을 예측하고 배합·숙성 조건 최적화를 지원",
      tags: ["품질 예측", "모델 벤치마크", "배합 최적화"],
      metrics: [["420", "학습 로트"], ["3", "비교 모델"]],
      url: "http://187.52.127.215:8022/",
      qr: "assets/qr/05.svg",
      image: "assets/shots/05-fold.png",
      tall: "",
      video: "",
      accent: "#a3e635",
      ink: "#4d7c0f",
    },
  ],
};
